In [1]:
import numpy as np


In [ ]:
# Applying MEA using 1. python, 2. Numpy

In [33]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3,1.7,1,0,0.5])

In [34]:
# mae using PYTHON

def mae(y_true,y_predicted):
    total_error = 0;
    for yt, yp in zip(y_true,y_predicted):
        print(f"{yt},{yp}")

        # to calculate absolute error
        total_error += abs(yt-yp)
    print('total error is:',total_error)
    mae =  total_error/len(y_true)
    print('total mean error is:',mae)
    return mae;

In [35]:
mae(y_true,y_predicted)

0.3,1
1.7,1
1.0,0
0.0,0
0.5,1
total error is: 2.9
total mean error is: 0.58


np.float64(0.58)

In [36]:
# MAE using NUMPY

MAE = np.mean(np.abs(y_true - y_predicted))
MAE

np.float64(0.58)

In [37]:
# above we can celarly see how easy mae definig/calculating in easy in numpy than that of python


In [38]:
# LOG LOSS APLICATION

In [39]:
np.log(0.000000000000000000000000000000000000000001)

np.float64(-96.70857390574992)

In [40]:
# if we are getting log zero in some calculation then it will create a trouble so taking a value close to zero can help us

In [41]:
epsilon = 1e-15

In [42]:
# here in predicted value there is presence of both 0,1 
# targeting zero

y_predicted_n= [max(i,epsilon) for i in y_predicted] 


In [43]:
y_predicted_n

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [44]:
y_predicted_n= [min(i,1-epsilon)  for i in y_predicted_n]
y_predicted_n


[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [45]:
y_predicted_n = np.array(y_predicted_n)

In [46]:
np.log(y_predicted_n)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [49]:
# creating a log loss

-np.mean(y_true*np.log(y_predicted_n) + (1-y_true)*np.log(1-y_predicted_n))

np.float64(10.361712878216224)

In [78]:
# creating a log loss finction

def log_l(y_true,y_predicted):
    epsilon = 1e-15
    print(y_predicted)
    y_predicted_n = [max(i,epsilon) for i in y_predicted]
    print(y_predicted_n)
    
    y_preidcted_n= [min(i,1-epsilon)  for i in y_predicted_n]
    y_predicted_n= [min(i,1-epsilon)  for i in y_predicted_n]
    print(y_predicted_n)
    
    y_predicted_n = np.array(y_predicted_n)
    print(y_predicted_n)
    # return -np.mean(y_true*np.log(y_predicted_n) + (1-y_true)*np.log(1-y_predicted_n))

In [61]:
np.log(y_predicted_n)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [79]:
log_l(y_true,y_predicted)

[1 1 0 0 1]
[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]
[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]
[1.e+00 1.e+00 1.e-15 1.e-15 1.e+00]
