In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras.models import Sequential



In [10]:
from tensorflow import keras

In [9]:
!pip install matplotlib

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 246.8 kB/s eta 0:00:31
   -- ------------------------------------- 0.5/8.1 MB 246.8 kB/s eta 0:00:31
   -- ------------------------------------- 0.5/8.1 MB 246.8 kB/s eta 0:00:31
   -- ------------------------------------- 0.5/8.1 MB 246.8 kB/s eta 0:00:31
   -- ------------------------------------- 0.5/8.1 MB 246.8 kB/s eta 0:

In [2]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('insurance.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
!pip install scikit-learn


  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.9 MB 560.1 kB/s eta 0:00:15
   --- ------------------------------------ 0.8/8.9 MB 819.2 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/8.9 MB 1.0 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/8.9 MB 932.1 kB/s eta 0:00:09
   ------- -------------------------------- 1.6/8.9 MB 953.2 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.9 MB 953.2 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.9 MB 953.2 kB/s eta 0:00:08
   -------- ------------------------------- 1.8/8.9 MB 799.2 kB/s eta 0:00:09
   ---------- ----------------------------- 2.4/8.9 MB 952.0 kB/s eta 0:00:07
   ---------- ----------

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [7]:
len(x_train)

22

In [8]:
# scaling of data
# casue age is not in the same range as affordibility
# from sklearn.preprocessing import StandardScaler
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age'] / 100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [14]:
# now we can create a neural network model


modle = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,), activation= 'sigmoid', kernel_initializer = 'ones', bias_initializer='zeros')
])

# input_shape = (2,)  - this means we have 2 features in our input data
# 1 - this means we have 1 output in our model
# activation= 'sigmoid' - this means we are using sigmoid activation function
# kernel_initializer = 'ones' - this means we are initializing the weights-(w) of the model with ones
# bias_initializer='zeros' - this means we are initializing the bias-(b) of the model with zeros

c:\Users\as\miniconda3\envs\tf\lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# now we can compile  the model

modle.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# optimizer='adam' - this means we are using adam optimizer
# loss='binary_crossentropy' - this means we are using binary crossentropy loss function its more efficient than that of other loss functions for binary classification problems as it suits best for gradeeint descent
# metrics=['accuracy'] - this means we are using accuracy as a metric to evaluate the model

In [20]:
modle.fit(x_train_scaled,y_train,epochs=5000,batch_size=32, validation_data=(x_test_scaled,y_test),)
#  batch_size=32, validation_data=(x_test_scaled,y_test)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 596ms/step - accuracy: 0.6818 - loss: 0.5956 - val_accuracy: 0.6667 - val_loss: 0.5783
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.6818 - loss: 0.5955 - val_accuracy: 0.6667 - val_loss: 0.5782
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - accuracy: 0.6818 - loss: 0.5955 - val_accuracy: 0.6667 - val_loss: 0.5782
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 318ms/step - accuracy: 0.6818 - loss: 0.5954 - val_accuracy: 0.6667 - val_loss: 0.5781
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.6818 - loss: 0.5954 - val_accuracy: 0.6667 - val_loss: 0.5780
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 0.6818 - loss: 0.5953 - val_accuracy: 0.6667 - val_loss: 0.5780
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.6818 - loss: 0.5953 - val_accuracy: 0.6667 - val_loss: 0.5779
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.6818 - loss: 0.5952 - val_accuracy: 0.

In [21]:
# now we can evaluate the model
loss, accuracy = modle.evaluate(x_test_scaled, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3152
Loss: 0.3152032494544983, Accuracy: 1.0


In [24]:
modle.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step


array([[0.71949804],
       [0.30730888],
       [0.13835008],
       [0.44827065],
       [0.743261  ],
       [0.85681343]], dtype=float32)

In [25]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [26]:
#  now we lets check weights (coefficient) and bias(intercept) of the model

coef, intercept = modle.get_weights()
coef, intercept

(array([[6.0507035],
        [1.5003872]], dtype=float32),
 array([-3.4022446], dtype=float32))

In [29]:
x_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [27]:
#  lets try same using python by creating a function

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [28]:
def predict(age, affordibility):
    weighted_sum = coef[0][0]*age + coef[1][0]* affordibility + intercept[0]
    return sigmoid(weighted_sum)

In [32]:
predict(0.47,1)
predict(0.18,1)
# yup the prediction is correct in python and int tensorflow

np.float32(0.3073089)

# NOW lets write the code for gradent descent 
# oftenly asked in interviews

In [34]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([0.47, 0.18,0]))

array([0.61538376, 0.54487889, 0.5       ])

In [ ]:
# def log_loss(y_true, y_predicted):
#     epsilon = 1e-15
#     y_predicted_new = [max(i,epsilon) for i in y_predicted]
#     y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
#     y_predicted_new = np.array(y_predicted_new)
#     return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [37]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred_n = [max(i,epsilon) for i in y_pred]
    y_pred_n = [min(i,epsilon) for i in y_pred_n]

    y_pred_n = np.array(y_pred_n)
    return -np.mean(y_true *np.log(y_pred_n)+(1-y_true)*np.log(1-y_pred_n))

In [45]:
def gradeint_descent(age, affordiblity,y_true, epochs,loss_thresold):
    w1 = w2 = 1
    b = 0
    rate = 0.5
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1*age + w2*affordiblity + b
        y_pred = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_true,y_pred)

        w1d = (1/n)*np.dot(np.transpose(age),(y_pred-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordiblity),(y_pred-y_true)) 

        bias_d = np.mean(y_pred-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        b = b - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{b}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, b


In [46]:
gradeint_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:17.26938819745534
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:17.26938819745534
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:17.26938819745534
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:17.26938819745534
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:17.26938819745534
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:17.26938819745534
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:17.26938819745534
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:17.26938819745534
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:17.26938819745534
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bias:-0.64

(np.float64(8.270239516056172),
 np.float64(1.6332228396255535),
 np.float64(-4.425953608965705))

In [47]:
coef, intercept

(array([[6.0507035],
        [1.5003872]], dtype=float32),
 array([-3.4022446], dtype=float32))

This shows that in the end we were able to come up with same value of w1,w2 and bias using a plain python implementation of gradient descent function